# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IM_iVGKxNVf1EMRpBNi-IVCeNfbYUkjb
"""

kullanici_adi='john'
sifre='23'
def login():
  deger=input('kullanıcı adını girin:')
  sifreDeger=input('sifre girin:')
  return giris(deger,sifreDeger)
login()
def giris(kAdi,sAdi):
  if kAdi==kullanici_adi and sAdi==sifre:
    print('Welcome John')
  else:
    print('Başarısız tekrar dene')
    return login();
 
words='Python'
wordSec=['*','*','*','*','*','*']
kelime=len(words)
print(f'kelimeniz {kelime} harfli')
hakSayisi=int(input(f'Kaç hak ile bitirebilirsin(min girilecek hak={kelime})?:'))
puan=100
soruPuanı=puan/hakSayisi

i=0
while hakSayisi>0:
  
  gelenDeger=input('İlk Harfinizi giriniz:')
  if gelenDeger in words:
    puan=puan-i*soruPuanı
    print(f'Tebrikler 1 kelimeyi buldunuz ve puanınız: {puan} ')
    b=words.index(gelenDeger)
    wordSec[b]=gelenDeger
    print(wordSec)
    
  else:
      print('başarısız deneme tekrar dene')
      hakSayisi=hakSayisi-1     
      i=i+1