# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IM_iVGKxNVf1EMRpBNi-IVCeNfbYUkjb
"""

kullanıcı=[]

kullanıcı.append(input('ad:'))
kullanıcı.append(input('Soyad:'))
kullanıcı.append(int(input('yas:')))
kullanıcı.append(int(input('dogum yili:')))

for i in range(1):
  print(kullanıcı)
  if kullanıcı[2]>18:
    print('Sokağa Çıkabilirsin')
  else:
    print('Dışara çıkamazsın çünkü çok tehlikeli')