# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IM_iVGKxNVf1EMRpBNi-IVCeNfbYUkjb
"""

for i in range(5):
  deger.append(input('deger girin:'))
  print(f'degeriniz:{deger[i]} ve type:{type(deger[i])}')