# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1so98SpWzFv6cit15WRkDK0smJPVMQW59
"""

def sec(dersim):
  derslera=dersim
  
  giris=True
  while giris:
      dersSayisi=int(input('kac ders seçeceksiniz(3 ila 5 arasında sayi giriniz)'))
      if 3 <= dersSayisi <= 5:
        print('denemen')
        giris=False
      else:
        print('3 ile 5 arasında girin')
  print(dersim)
  '''derssec=int(input('Kaç Numaralı Dersi Seçeceksin?'))'''
  aldersler=[]
  print(dersim)
  for i in range(dersSayisi):
    y=int(input('Dersleri girin:'))
    aldersler.append(y) 
    
  print(aldersler)
  sinavdersi=int(input('Hangi Ders?'))
  
  a=int(input('Ara Sınav Notu'))
  b=int(input('Final Notu'))
  c=int(input('Proje Notu'))

  not_dict = {'Ara Sınav':a,'Final':b,'Proje':c}
  print(not_dict)
  notx=a*(30/100)+b*(50/100)+c*(20/100)
  print(notx)

  if notx < 30:
        print("harf notunuz: FF")
        print("dersi geçemediniz")
  elif notx >= 30 and notx < 50:
        print("harf notunuz: DD")
  elif notx >= 50 and notx < 70:
        print("harf notunuz: CC")
  elif notx >= 70 and notx < 90:
        print("harf notunuz: BB")
  elif notx >= 90:
        print("harf notunuz: AA")


   

    


def dersx():
  dersler=[]
  for i in range(5):
    dersler+=input('Dersleri girin:')
    print(dersler)
  sec(dersler)

def login():
  adSoy='emir said erdemir'
  sayac=0
  giris=False
  while sayac<3:
    if giris==False:
      isSoy=input('Adınızı ve soyadınızı girin:')
      adSoy.lower()
      isSoy.lower()
      if isSoy==adSoy:
        print('Hoşgeldiniz')
        giris=True
        sayac=3
      else:
        print('Başarısız Giriş')
        sayac+=1

    if giris==True:
      dersx()

login()